-- BOE Gaming Demo - Grants
-- ============================================================================
-- All grants for the demo, organized by deployment phase.
-- Requires: ACCOUNTADMIN role
-- Run after: 01_database_schema.sql
-- ============================================================================

USE ROLE IDENTIFIER($ADMIN_ROLE);

-- =============================================================================
-- SECTION A: Initial Access Grants
-- Run immediately after database/schema creation
-- =============================================================================

-- Database access
GRANT USAGE ON DATABASE DEDEMO TO ROLE IDENTIFIER($RUNTIME_ROLE);

-- CREATE SCHEMA required for CDC connector (creates TOURNAMENTS schema)
GRANT CREATE SCHEMA ON DATABASE DEDEMO TO ROLE IDENTIFIER($RUNTIME_ROLE);

-- Warehouse access
GRANT USAGE ON WAREHOUSE IDENTIFIER($WAREHOUSE_NAME) TO ROLE IDENTIFIER($RUNTIME_ROLE);

-- Schema access and object creation privileges
GRANT USAGE ON SCHEMA DEDEMO.GAMING TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT CREATE TABLE ON SCHEMA DEDEMO.GAMING TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT CREATE FUNCTION ON SCHEMA DEDEMO.GAMING TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT CREATE PROCEDURE ON SCHEMA DEDEMO.GAMING TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT CREATE STREAM ON SCHEMA DEDEMO.GAMING TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT CREATE DYNAMIC TABLE ON SCHEMA DEDEMO.GAMING TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT CREATE VIEW ON SCHEMA DEDEMO.GAMING TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT CREATE STREAMLIT ON SCHEMA DEDEMO.GAMING TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT CREATE STAGE ON SCHEMA DEDEMO.GAMING TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT CREATE SEQUENCE ON SCHEMA DEDEMO.GAMING TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT CREATE SEMANTIC VIEW ON SCHEMA DEDEMO.GAMING TO ROLE IDENTIFIER($RUNTIME_ROLE);

-- Future grants for CDC-created objects
GRANT SELECT ON FUTURE TABLES IN DATABASE DEDEMO TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE DEDEMO TO ROLE IDENTIFIER($RUNTIME_ROLE);

-- =============================================================================
-- SECTION B: Object Grants
-- These grant access to objects created by the SQL scripts.
-- Run after all objects are created (tables, DT, stream, views, function, procedure).
-- =============================================================================

-- Tables
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DEDEMO.GAMING.BATCH_STAGING TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DEDEMO.GAMING.REGULATORY_BATCHES TO ROLE IDENTIFIER($RUNTIME_ROLE);

-- Dynamic table
GRANT SELECT ON DYNAMIC TABLE DEDEMO.GAMING.DT_POKER_FLATTENED TO ROLE IDENTIFIER($RUNTIME_ROLE);

-- Stream
GRANT SELECT ON STREAM DEDEMO.GAMING.POKER_TRANSACTIONS_STREAM TO ROLE IDENTIFIER($RUNTIME_ROLE);

-- Function and procedure
GRANT USAGE ON FUNCTION DEDEMO.GAMING.GENERATE_POKER_XML_JS(VARIANT, VARCHAR, VARCHAR, VARCHAR) TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT USAGE ON PROCEDURE DEDEMO.GAMING.PROCESS_STAGED_BATCH(VARCHAR) TO ROLE IDENTIFIER($RUNTIME_ROLE);

-- Observability views
GRANT SELECT ON VIEW DEDEMO.GAMING.PIPELINE_LATENCY_ANALYSIS TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT SELECT ON VIEW DEDEMO.GAMING.PIPELINE_LATENCY_DETAIL TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT SELECT ON VIEW DEDEMO.GAMING.OPENFLOW_LOGS TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT SELECT ON VIEW DEDEMO.GAMING.OPENFLOW_ERROR_SUMMARY TO ROLE IDENTIFIER($RUNTIME_ROLE);

-- =============================================================================
-- SECTION C: Specification Extraction Objects
-- Grants for objects created by SharePoint CDC connector and AI extraction.
-- Run after SharePoint connector has created tables and stage.
-- =============================================================================

-- Stage access for Document AI
GRANT READ ON STAGE DEDEMO.GAMING.DOCUMENTS TO ROLE IDENTIFIER($RUNTIME_ROLE);

-- SharePoint CDC tables (created by connector)
GRANT SELECT ON TABLE DEDEMO.GAMING.DOC_METADATA TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT SELECT ON TABLE DEDEMO.GAMING.FILE_HASHES TO ROLE IDENTIFIER($RUNTIME_ROLE);

-- AI extraction tables
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DEDEMO.GAMING.BOE_DOCUMENT_EXTRACTED TO ROLE IDENTIFIER($RUNTIME_ROLE);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DEDEMO.GAMING.AI_OUTPUTS TO ROLE IDENTIFIER($RUNTIME_ROLE);

-- Semantic view
GRANT USAGE ON SEMANTIC VIEW DEDEMO.GAMING.GAMING_PIPELINE_ANALYTICS TO ROLE IDENTIFIER($RUNTIME_ROLE);

-- =============================================================================
-- Verification
-- =============================================================================
SELECT 'Grants applied' AS status;
