-- BOE Gaming Demo - Tables
-- ============================================================================
-- Creates staging and audit tables for batch processing.
-- Run after: 02_grants.sql
-- ============================================================================

USE ROLE IDENTIFIER($RUNTIME_ROLE);
USE SCHEMA DEDEMO.GAMING;

-- Temporary storage for batch inserts before XML generation
CREATE OR REPLACE TABLE DEDEMO.GAMING.BATCH_STAGING (
    TRANSACTION_ID VARCHAR(16777216),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
    TOURNAMENT_ID VARCHAR(16777216),
    TOURNAMENT_NAME VARCHAR(16777216),
    TOURNAMENT_START VARCHAR(16777216),
    TOURNAMENT_END VARCHAR(16777216),
    VARIANT VARCHAR(16777216),
    VARIANT_COMMERCIAL VARCHAR(16777216),
    PLAYER_ID VARCHAR(16777216),
    BET_AMOUNT NUMBER(10,2),
    REFUND_AMOUNT NUMBER(10,2),
    WIN_AMOUNT NUMBER(10,2),
    PLAYER_IP VARCHAR(16777216),
    DEVICE_TYPE VARCHAR(16777216),
    DEVICE_ID VARCHAR(16777216),
    BATCH_INSERT_TIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID VARCHAR(16777216)
)
COMMENT = 'Temporary staging for batch inserts before XML generation';

-- Audit table tracking batch lifecycle from generation through SFTP upload
CREATE OR REPLACE TABLE DEDEMO.GAMING.REGULATORY_BATCHES (
    BATCH_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    OPERATOR_ID VARCHAR(4),
    WAREHOUSE_ID VARCHAR(10),
    BATCH_TIMESTAMP TIMESTAMP_NTZ(9),
    TRANSACTION_COUNT NUMBER(38,0),
    GENERATED_XML VARCHAR(16777216),
    STATUS VARCHAR(20),
    UPLOAD_TIMESTAMP TIMESTAMP_NTZ(9),
    GENERATED_FILENAME VARCHAR(500),
    SFTP_DIRECTORY_PATH VARCHAR(1000)
)
COMMENT = 'Audit table tracking batch lifecycle: GENERATED -> UPLOADED';

-- Verify
SELECT 'Tables created' AS status;
SHOW TABLES IN SCHEMA DEDEMO.GAMING;
